version: "3"

networks:
  kong-net:
    driver: bridge

services:
  #######################################
  # PostgreSQL: Database for Kong
  #######################################
  kong-database:
    image: postgres:16
    container_name: kong-database
    restart: always
    networks:
      - kong-net
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  #######################################
  # Kong database migration (run once)
  #######################################
  kong-migration:
    image: kong:latest
    container_name: kong-migration
    command: ["kong", "migrations", "bootstrap"]
    networks:
      - kong-net
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
    depends_on:
      - kong-database

  #######################################
  # Kong: API Gateway + Kong Manager
  #######################################
  kong:
    image: kong:latest
    container_name: kong
    restart: always
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong

      # Proxy (API Gateway)
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl

      # Admin API
      KONG_ADMIN_LISTEN: 0.0.0.0:8001

      # Kong Manager (GUI)
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002, 0.0.0.0:8445 ssl
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_ADMIN_GUI_SESSION_CONF: '{"secret":"supersecretkey","storage":"kong"}'
      KONG_ADMIN_GUI_AUTH: basic-auth
      KONG_ADMIN_GUI_USERNAME: admin
      KONG_ADMIN_GUI_PASSWORD: admin123

      # Optional (CORS)
      KONG_HEADERS: "off"

    depends_on:
      kong-migration:
        condition: service_completed_successfully
      kong-database:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 5s
      timeout: 2s
      retries: 15

    ports:
      - "8000:8000"   # Kong Proxy
      - "8443:8443"   # Kong Proxy SSL
      - "8001:8001"   # Kong Admin API
      - "8002:8002"   # Kong Manager (GUI)
      - "8445:8445"   # Kong Manager (SSL)