version: "3"

networks:
  kong-net:
    driver: bridge

services:
  #######################################
  # PostgreSQL: Database used by Kong & Konga
  #######################################
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    restart: always
    networks:
      - kong-net
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  #######################################
  # Kong database migration (run once)
  #######################################
  kong-migration:
    image: kong:latest
    container_name: kong-migration
    command: [ "kong", "migrations", "bootstrap" ]
    networks:
      - kong-net
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
    depends_on:
      - kong-database

  #######################################
  # Kong: API Gateway
  #######################################
  kong:
    image: kong:latest
    container_name: kong
    restart: always
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      kong-migration:
        condition: service_completed_successfully
      kong-database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"

  #######################################
  # Konga DB Preparation (Run Once)
  #######################################
  konga-prepare:
    image: pantsel/konga:next
    container_name: konga-prepare
    command: [ "-c", "prepare", "-a", "postgres", "-u", "postgresql://kong:kong@kong-database:5432/konga_db" ]
    networks:
      - kong-net
    restart: on-failure
    depends_on:
      - kong-database

  #######################################
  # Konga: Admin GUI for Kong
  #######################################
  konga:
    image: pantsel/konga:next
    container_name: konga
    restart: always
    networks:
      - kong-net
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_PORT: 5432
      DB_USER: kong
      DB_PASSWORD: kong
      DB_DATABASE: konga_db
      NODE_ENV: production
      TOKEN_SECRET: km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
      KONGA_ADMIN_EMAIL: admin@admin.com
      KONGA_ADMIN_PASSWORD: admin123
    depends_on:
      - kong
    ports:
      - "1337:1337"
